# This workflow will build a Java project with Gradle, publish image to DockerHub and run it.

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      DOCKER_HUB_USER: devopsgoofy
      DOCKER_IMAGE_NAME: gradle-proj

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Increment patch version
        id: increment_version
        run: |
          ./increment_version.sh

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@cf8c4352603fd732e2c354bcdbe793fe7dc885dc # V4.1.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build -DsourceSets.main.java.srcDirs=src/main/java
        
      - name: List files in build/libs
        run: |
          ls gradle-hello-world/build/libs

      - name: Package into JAR
        run: ./gradlew shadowJar --info 

      - name: Create Docker image
        run: |
          docker build -t ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.increment_version.outputs.version }} .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ env.DOCKER_HUB_USER }} --password-stdin

      - name: Publish Docker image
        run: |
          docker push ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.increment_version.outputs.version }}

      - name: Run Docker container
        run: |
          docker run --rm --user 1001:1001 ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.increment_version.outputs.version }}

      - name: Push changes back to repo
        run: |
          git add .
          git commit -m "Workflow complete. Changed version to ${{ steps.increment_version.outputs.version }}"
          git push origin master
