name: Java CI/CD with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [closed]
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USER: devopsgoofy
      DOCKER_IMAGE_NAME: gradle-proj

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Increment patch version
        id: increment_version
        run: |
          VERSION=$(awk -F ' = "' '/^version =/ {print $2}' build.gradle.kts | tr -d '"')
          echo "Current version: $VERSION"
          IFS='.' read -r major minor patch <<< "$VERSION"
          new_patch=$((patch + 1))
          new_version="$major.$minor.$new_patch"
          echo "New version: $new_version"
          echo "version=$new_version" >> $GITHUB_OUTPUT
          sed -i "s/version = \".*\"/version = \"$new_version\"/" build.gradle.kts

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Publish Docker image
        uses: docker/build-push-action@23c657a01f105567f668c7596ce8e5a038da2555 # V6.7.0
        with:
          context: .
          file: Dockerfile
          tags: ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.increment_version.outputs.version }}
          build-args: |
            JAR_VERSION=${{ steps.increment_version.outputs.version }}
          push: true

      - name: Run Docker container
        run: |
          docker run --rm ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.increment_version.outputs.version }}

      - name: Push changes back to repo
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Actions"
          git switch master
          git add .
          git commit -m "Workflow complete. Changed version to ${{ steps.increment_version.outputs.version }} [skip ci]"
          git push origin master
