# This workflow will build a Java project with Gradle
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Increment patch version
        run: |
          ./increment_version.sh

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@cf8c4352603fd732e2c354bcdbe793fe7dc885dc # V4.1.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Package into JAR
        run: ./gradlew shadowJar
